version: '3.7'

services:
  app:
    container_name: app
    image: app_image
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src
    ports:
      - ${PORT_EXTERN}:${PORT}
    depends_on:
      - app_db
      - app_redis

  app_db:
    container_name: app_db
    hostname: ${POSTGRES_HOST}
    image: library/postgres:14.1
    env_file:
      - .env
    volumes:
      - app_db_data:/var/lib/postgresql/data
      - app_db_backups:/backups
      - ./scripts/postgres:/scripts
    ports:
      - "${POSTGRES_PORT}:5432"

  app_db_admin:
    container_name: app_pgadmin
    image: dpage/pgadmin4:latest
    # restart: unless-stopped
    # mem_reservation: 256m
    env_file:
      - .env
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - app_pgadmin_data:/var/lib/pgadmin
    depends_on:
      - app_db

  app_redis:
    image: redis:6.2-alpine
    hostname: redis
    container_name: app_redis
    command:
      - 'redis-server'
      - '--requirepass myStrongPassword'
    ports:
      - ${REDIS_PORT}:6379

volumes:
  app_db_data:
    driver: "local"
  app_db_backups:
    driver: "local"
  app_pgadmin_data:
    driver: "local"

networks:
  default:
    external: true
    name: app_net
